### ISSUE TITLE
MEX - Maria Josepha Sophia and the "Dominant-Party Republic"

### ISSUE THREAD

**Issue by Stratilys** [JoeBidenWhatAreYouHiding/kx#55]
Maria Josepha Sophia's name is still rendered very awkwardly. First name in Spanish, other two in English/German, she was never called "Josephia", and with an out-of-place regnal number tacked on the end. Change the localisation for her name from "María Josephia Sophia I" to just "María I" or "María Josefa Sofía" because the amalgamated current incarnation is really bugging me.

Also, one of the final non-revolutionary democratic focuses is called Dominant-Party Republic and gives a national idea with the same name even if you're not a republic. Just go with Dominant-Party Democracy or something.

**Comment by Polskers** [comment]
I believe this was already fixed in a prior build, was it not? At least, the name of the monarch is now María I de Iturbide.

I'll check on "Dominant-Party Republic" though.

**Comment by Polskers** [comment]
Fixed and pushed to Git.
